### ISSUE TITLE
Version number issues? Play store consistently wants to update the Github version?

### ISSUE THREAD

**Issue by twizzlebizzle** [michaldrabik/showly-2.0#826]
If you have an idea for a new feature or how to improve the app please use [Discussions](https://github.com/michaldrabik/showly-2.0/discussions) for that purpose.

**Describe the bug**
I have Showly installed from the latest version from github.  Works perfecr, however the play store consistently wants to update the app, when I try it fails (presumably because of the different signing keys?).

**Expected behavior**
Github version should be the same or newer and not constantly ask for an update?

**Screenshots**
Please see the screenshot of the playstore issue.

![Screenshot_20240609-121113](https://github.com/michaldrabik/showly-2.0/assets/11423542/146e0411-4cbf-4c03-b20d-bf9f19981724)

**Comment by michaldrabik** [comment]
Probably caused because package name is the same and verson code is lower. I will try bumping that with next update which should probably solve it.

**Comment by michaldrabik** [comment]
Hopefully it is now fixed after latest 3.37.1 release.

**Comment by twizzlebizzle** [comment]
> Hopefully it is now fixed after latest 3.37.1 release.

Hi, its not fixed.
Updated this morning and the play store still has this issue...

Thank you, tried clearing the play store cache, but it still persists

**Comment by michaldrabik** [comment]
Then it means that package name would need to be changed. The only downside is that after the change you won't be able to make a first update and basically reinstall the app.

**Comment by twizzlebizzle** [comment]
> Then it means that package name would need to be changed. The only downside is that after the change you won't be able to make a first update and basically reinstall the app.

That doesn't seem ideal.
Is anyone else experiencing this?
